### ISSUE TITLE
Plugins loaded but now working

### ISSUE THREAD

**Issue by alphamodel** [jGleitz/markdown-it-prism#71] opened 2020-06-09 14:50 UTC
Following is the input js file:

```const md = require('markdown-it')();
const prism = require('markdown-it-prism');
const options = {
	plugins: ["line-highlight","show-language"]
};
md.use(prism, options);

console.log(md.render(`
\`\`\`python {3,5}
import os
import sys
\`\`\`
`
)); 
````
output file is following:

```html
<pre class="language-python"><code class="language-python"><span class="token keyword">import</span> os
<span class="token keyword">import</span> sys

</code></pre>
```

It looks like the two plugins do not has any effects.

**Comment by jGleitz** [comment] 2020-06-11 10:23
Hi and thanks for reporting this bug!

Both `line-highlight` and `show-language` are plugins that rely on the DOM being present (although they would not need to do that). They are programmed to not do anything if there is no DOM (see [`line-highlight.js#3`](https://github.com/PrismJS/prism/blob/master/plugins/line-highlight/prism-line-highlight.js#L3) and [`prism-show-language.js#3`](https://github.com/PrismJS/prism/blob/master/plugins/show-language/prism-show-language.js#L3). There is no DOM when rendering markdown with `markdown-it` because `markdown-it`, like any Markdown parser, operates on text tokens. So, unfortunately, this is nothing we can fix in this plugin. The Prism plugins need to be re-written in order to make them work.

In this sense, this bug is a duplicate of #1, for which there already is a warning in the `README`:

> Please note that some prism plugins (notably line-numbers) rely on the DOM being present and can thus not be used with this package (see #1).

Thus, I am going to close this bug. Sorry that we cannot be more helpful!

**Closed by jGleitz** 2020-06-11 10:23 UTC
