### ISSUE TITLE
markdown-it-prism: after importing Critical dependency issues come out

### ISSUE THREAD

**Issue by afsarpervez** [jGleitz/markdown-it-prism#313] opened 2021-06-08 17:42 UTC
```
WARNING in ./node_modules/prismjs/components/index.js 42:23-54
Critical dependency: the request of a dependency is an expression
```
My code part that causing the problem while using with WebPack
`import prism from 'markdown-it-prism';`

farther code lines:
```
const md = new MarkdownIt();
md.use(prism);
```

I tried changing versions for different laravel mix, vue, and markdown-it-prism packages. But nothing changed.  This problem only omitted when I remove the `markdown-it-prism` import.

**Comment by jGleitz** [comment] 2021-07-03 07:16
Hi, thanks for the report (and sorry for the late response).

I think this problem is part of the fact that this plugin does not work very well with Webpack. So far, nobody has come up with a good solution for this. The main cause of the issue is that we need to load the language dynamically by including their files, an approach that (naturally) doesn’t work well with Webpack. I have given some hints in the `README` about how to circumvent this, but it is certainly not ideal.

Apart from the warning, does `markdown-it-prism` work for you if you include the languages manually, as explained in the `README`?

**Comment by NOPR9D** [comment] 2022-01-07 19:20
download prismjs from : https://prismjs.com

and use like this :

![image](https://user-images.githubusercontent.com/75882457/148595818-ffd25f07-83ce-444e-b6af-e198d973e856.png)


Good luck

**Comment by jGleitz** [comment] 2022-01-21 22:41
I am closing this as a duplicate of #28

**Closed by jGleitz** 2022-01-21 22:41 UTC
